#!/bin/bash

# Change to directory with test data
DIRECTORY=""

# Search for .tex files in test_data directory and add to an array.
TEX_FILES=$(find "$DIRECTORY" -name '*.tex')
TEX_FILES=${TEX_FILES[0]}
IFS=$'\n' read -rd '' -a TEX_FILES<<<"$TEX_FILES"

# Iterates through .tex fiels and send them to python script
# Right now I'm skipping files that are examples since they crashed the python script.
for f in "${TEX_FILES[@]}"; do
  if echo "$f" | grep -iqFv 'example' ; then
    echo "Starting python script with $f"
    python3 main.py "$f" &
  fi
done
